# 默认的profile为dev，其他环境通过指定启动参数使用不同的profile，比如：
#   测试环境：java -jar my-spring-boot.jar --spring.profiles.active=test
#   生产环境：java -jar my-spring-boot.jar --spring.profiles.active=prod
spring:
  profiles:
    active: dev
  cache:
    type: CAFFEINE #指定cache类型
    cache-names:
      - selectAll458
      - name2
    caffeine:
      spec: maximumSize=500,expireAfterWrite=5s
      
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    hikari: # 数据库连接池，号称“史上最快链接池” https://github.com/brettwooldridge/HikariCP
      maxLifetime: 1765000 #一个连接的生命时长（毫秒），超时而且没被使用则被释放（retired），缺省:30分钟，建议设置比数据库超时时长少30秒以上
      maximumPoolSize: 15 #连接池中允许的最大连接数。缺省值：10；推荐的公式：((core_count * 2) + effective_spindle_count)

  mail:
    host: smtp.126.com
    username: youraccount
    password: yourpwd
    properties:
      mail:
        smtp: 
          auth: true
          starttls:
            enable: true
            required: true

mybatis:
  mapperLocations: classpath:mapper/*/*.xml
    
server:
  port: 8083
management:
  port: 54001
  health:
    mail:
      enabled: false
info:
  app:
    name: "@project.name@" #从pom.xml中获取
    description: "@project.description@"
    version: "@project.version@"
    spring-boot-version: "@project.parent.version@"
      
---
# 开发环境配置
spring:
  jpa:
     hibernate:
       ddl-auto: update
  profiles: dev
  redis:
    database: 3      # Redis数据库索引（默认为0）
    host: localhost  # Redis服务器地址
    port: 6379       # Redis服务器连接端口
    password:        # Redis服务器连接密码（默认为空）
    timeout: 3000       # 连接超时时间（毫秒）
    pool:
      max-active: 8  # 连接池最大连接数（使用负值表示没有限制）
      max-idle: 8    # 连接池中的最大空闲连接
      max-wait: -1   # 连接池最大阻塞等待时间（使用负值表示没有限制）
      min-idle: 0    # 连接池中的最小空闲连接
    #cluster:
     # nodes:
       # - 127.0.0.1:6379
       # - 192.168.0.17:6391
       # - 192.168.0.17:6392
       # - 192.168.0.9:6390
       # - 192.168.0.9:6391
       # - 192.168.0.9:6392
  datasource:
    url: jdbc:mysql://localhost:3306/sbt?autoReconnect=true&useSSL=false&useUnicode=true&characterEncoding=utf8
  data:
    mongodb:
      uri: mongodb://localhost:27017/sbt
      
#自定义的属性和值
myconfig: 
  simpleProp: simplePropValue
  arrayProps: 1,2,3,4,5
  listProp1:
    - name: abc
      value: abcValue
    - name: efg
      value: efgValue
  listProp2:
    - config2Value1
    - config2Vavlue2
  mapProps:
    key1: value1
    key2: value2
  
---
# 测试环境配置
spring:
  profiles: test
  datasource:
    url: jdbc:mysql://192.168.0.12:3306/
  
---
# 生产环境配置
spring:
  profiles: prod
  datasource:
    url: jdbc:mysql://192.168.0.13:3306/